stages:
    - build-app
    - deploy-app

build_app:
    stage: build-app
    image: node:18
    rules:
        - if: '$CI_COMMIT_TAG'
    script:
        - npm ci
        - npm run build
    artifacts:
        paths:
            - out
        expire_in: 1 day

deploy_app:
    stage: deploy-app
    rules:
        - if: '$CI_COMMIT_TAG'
    script:
        - apk add samba-client
        - smbclient -U $SMB_USERNAME --password=$SMB_PASSWORD //$SMB_SERVER_NAME/ozgportal -c "prompt OFF; recurse ON; deltree *; lcd out; mput *"
